version: "3.3"

services:
  matrix_app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    env_file:
      - .env
    ports:
      - ${APP_PORT}:8000
    command: gunicorn --workers 1  app.main:app
